import {
  EOS_NET_HOST,
  GOOGLE_WEB_CLIENT_ID,
  BIT_FITNESS_EOS_ACC,
  BIT_FITNESS_EOS_PUB_KEY,
} from '@env';

export const EnvVars = {
  EOSNETHOST: EOS_NET_HOST,
  GOOGLEWEBCLIENTID: GOOGLE_WEB_CLIENT_ID,
  BITFITNESSEOSACC: BIT_FITNESS_EOS_ACC,
  BITFITNESSEOSPUBKEY: BIT_FITNESS_EOS_PUB_KEY,
};
